### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ximanta** [jas-chen/react-dnd-card#1]
Running npm install --save react-dnd react-dnd-html5-backend react-dnd-card
reports the following error

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-dnd" "react-dnd-html5-backend" "react-dnd-card"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install react-dnd-card as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\simanta\Immersive\react-dnd-card-master\npm-debug.log

**Comment by jas-chen** [comment]
http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/
